// import type { CapacitorConfig } from '@capacitor/cli';

// const config: CapacitorConfig = {
//   appId: 'com.doctoro.app',
//   appName: 'Doctoro',
//   webDir: 'public'
// };

// export default config;


import { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.doctoro.app',
  appName: 'Doctoro',
  webDir: 'out', // Must match the folder generated by Next.js export
  // For static deployment, do not set a server.url
};

export default config;
